name: Solution Deploy

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Acción a ejecutar'
        type: choice
        options:
          - deploy
          - destroy
        default: 'deploy'
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    if: inputs.action == 'deploy'
    runs-on: ubuntu-latest
    steps:
      - name: Call Infrastructure Deploy
        uses: ./.github/workflows/infrastructure.yml
        with:
          action: apply

      - name: Call App Deploy
        uses: ./.github/workflows/app.yml
        with:
          action: deploy

  destroy:
    if: inputs.action == 'destroy'
    runs-on: ubuntu-latest
    steps:
      - name: Call Infrastructure Destroy
        uses: ./.github/workflows/infrastructure.yml
        with:
          action: destroy