name: Solution Deploy

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Acción a ejecutar'
        type: choice
        options:
          - deploy
          - destroy
        default: 'deploy'
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    if: inputs.action == 'deploy'
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Infrastructure Apply
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Infrastructure Deploy
          ref: main
          inputs: '{"action": "apply"}'
          token: ${{ secrets.WORKFLOW_DISPATCH_TOKEN }}

      - name: Wait for Infrastructure (12 minutes)
        run: sleep 720   # Espera 12 minutos (720 segundos)

      - name: Trigger App Deploy
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: App Deploy
          ref: main
          inputs: '{"action": "deploy"}'
          token: ${{ secrets.WORKFLOW_DISPATCH_TOKEN }}

  destroy:
    if: inputs.action == 'destroy'
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Infrastructure Destroy
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Infrastructure Deploy
          ref: main
          inputs: '{"action": "destroy"}'
          token: ${{ secrets.WORKFLOW_DISPATCH_TOKEN }}