name: Solution Deploy

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Acción a ejecutar'
        type: choice
        options:
          - deploy
          - destroy
        default: 'deploy'
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  call-infrastructure:
    name: Call Infrastructure Deploy
    uses: ./.github/workflows/infrastructure.yml
    with:
      action: apply
    if: inputs.action == 'deploy'

  call-app:
    name: Call App Deploy
    uses: ./.github/workflows/app.yml
    with:
      action: deploy
    needs: call-infrastructure
    if: inputs.action == 'deploy'

  call-infrastructure-destroy:
    name: Call Infrastructure Destroy
    uses: ./.github/workflows/infrastructure.yml
    with:
      action: destroy
    if: inputs.action == 'destroy'